function [dlds_threshold ...
          amp_threshold ...
          lateral_threshold ...
          heeltoe_threshold] = CalculateDiffThresholds(prediction_graph)
% CalcluateDiffThresholds Calculates thresholds for sensor graph pruning.

  g = abs(prediction_graph);
  dlds_threshold = quantile(reshape(g(:,:,1), 1, ...
                                    numel(g(:,:,1))), 0.5);
  amp_threshold = quantile(reshape(g(:,:,2), 1, ...
                                  numel(g(:,:,2))), 0.5);
  lateral_threshold = quantile(reshape(g(:,:,3), 1, ...
                                      numel(g(:,:,3))), 0.5);
  heeltoe_threshold = quantile(reshape(g(:,:,4), 1, ...
                                      numel(g(:,:,4))), 0.5);
