function [s v m] = SelectSensors(sensors_to_select, ...
                                 g, ...
                                 K1, ...
                                 K2, ...
                                 dlds, ...
                                 amp, ...
                                 lateral, ...
                                 heeltoe, ...
                                 dlds_at_sensor, ...
                                 amp_at_sensor, ...
                                 land_at_sensor)
  LoadConstants;

  [num_steps num_sensors] = size(dlds_at_sensor);

  s = logical(zeros(sensors_to_select, K2, num_sensors));
  v = logical(ones(sensors_to_select, K2, num_sensors));
  m = zeros(sensors_to_select, K2, 4);

  s_0 = logical(zeros(1, num_sensors));
  v_0 = logical(ones(1, num_sensors));

  for select = 1:sensors_to_select
    h = waitbar(0, sprintf('... Selecting Sensor %d ...', select));

    s_K2 = logical(zeros(K1*K2, num_sensors));
    v_K2 = logical(ones(K1*K2, num_sensors));
    m_K2 = zeros(K1*K2, 4);

    [num_configs nada] = size(s_0);
    next_config = 1;
    for c = 1:num_configs
      waitbar(c / num_configs, h);

      [s_1 v_1 m_1] = AddSensor(s_0(c,:), ...
                                v_0(c,:), ...
                                g, ...
                                K1, ...
                                dlds, ...
                                amp, ...
                                lateral, ...
                                heeltoe, ...
                                dlds_at_sensor, ...
                                amp_at_sensor, ...
                                land_at_sensor);
      [configs_added nada] = size(s_1);

      s_K2(next_config:(next_config+configs_added-1),:) = s_1;
      v_K2(next_config:(next_config+configs_added-1),:) = v_1;
      m_K2(next_config:(next_config+configs_added-1),:) = m_1;

      next_config = next_config + configs_added;
    end

    % strip off trailing predictions from initialization
    m_K2 = m_K2(1:next_config-1,:);

    % rank predictors
    [ranked_indices, thresholds_reached] = ...
        RankByThresholdDirection(m_K2, ...
                                 config.ranking_error_thresholds, ...
                                 config.ranking_error_directions);

    % keep at most top K2 predictors
    if next_config-1 > K2
      ranked_indices = ranked_indices(1:K2);
    end
    s_0 = s_K2(ranked_indices,:);
    v_0 = v_K2(ranked_indices,:);
    m_0 = m_K2(ranked_indices,:);

    s(select,:,:) = s_0;
    v(select,:,:) = v_0;
    m(select,:,:) = m_0;
  end
