function r = SubSample(s, ...
                       data, ...
                       step_starts, ...
                       step_ends, ...
                       dlds, ...
                       amp, ... 
                       lateral, ...
                       heeltoe)
step_length = max(step_starts - step_ends);
